# Generated by Django 4.2.3 on 2023-11-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_category_comment_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='price',
            new_name='starting_bid',
        ),
    ]
