# Generated by Django 4.2.3 on 2023-11-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='isActive',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
