# Generated by Django 4.2.3 on 2023-11-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlisting_isactive_auctionlisting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
