# Generated by Django 4.2.3 on 2023-11-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_winner_alter_auctionlisting_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
